imports:
    - { resource: config.yml }

web_profiler:


    # display the web debug toolbar at the bottom of pages with
    # a summary of profiler info
    toolbar:              true
    position:             bottom

    # gives you the opportunity to look at the collected data
    # before following the redirect
    intercept_redirects: false

    # Exclude AJAX requests in the web debug toolbar for specified paths
    excluded_ajax_paths:  ^/bundles|^/_wdt