services:
    # app.product:
    #     class: App\Controller\ProductController
    #     calls:
    #         - [setContainer, ['@service_container']]

    app.service.search:
        class: App\Services\SearchService
        arguments:
          - '@form.factory'
          - '@doctrine'

    app.token_authenticator:
        class: App\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']
