services:

    app.service.search:
        class: App\Services\SearchService
        arguments:
          - '@doctrine'
          - '@app.service.reservation'
          - '@app.service.prices'

    app.service.reservation:
        class: App\Services\ReservationService
        arguments:
          - '@doctrine'

    app.service.prices:
        class: App\Services\PricesService
        arguments:
          - '@doctrine'

    app.token_authenticator:
        class: App\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']
